This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./bwlimvorlage.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file bwlimvorlage.acn....done (9 entries accepted, 0 rejected).
Sorting entries....done (28 comparisons).
Generating output file bwlimvorlage.acr....done (14 lines written, 0 warnings).
Output written in bwlimvorlage.acr.
Transcript written in bwlimvorlage.alg.
